prueba

diff --git a/.github/workflows/branch_protection.yml b/.github/workflows/branch_protection.yml
--- a/.github/workflows/branch_protection.yml
+++ b/.github/workflows/branch_protection.yml
@@ -9,9 +9,23 @@ jobs:
     steps:
       - name: Verificar nombre de la rama
         run: |
-            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
-            if [[ ! "$BRANCH_NAME" =~ ^(feature)/ || ! "$BRANCH_NAME" =~ ^(release)/[0-9]\.[0-9]\.[0-9] ]]; then
+            # Obtener el nombre de la referencia
+            REF_NAME="${GITHUB_REF#refs/}"
+
+            # Verificar si la referencia es una rama
+            if [[ "$GITHUB_REF" == refs/heads/* ]]; then
+                BRANCH_NAME="${REF_NAME#heads/}"
+
+                # Validar el nombre de la rama
+                if [[ ! "$BRANCH_NAME" =~ ^(feature/) || ! "$BRANCH_NAME" =~ ^(release/[0-9]+\.[0-9]+\.[0-9]+) ]]; then
                 echo "Error: El nombre de la rama '$BRANCH_NAME' no cumple con el formato esperado."
+                exit 1
+                fi
+            elif [[ "$GITHUB_REF" == refs/pull/* ]]; then
+                echo "Error: El flujo de trabajo no debe ejecutarse en pull requests."
+                exit 1
+            else
+                echo "Error: Tipo de referencia no soportado: '$GITHUB_REF'."
                 exit 1
             fi
   # Validación para feature/* a develop
